//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldenacre.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Goldenacre_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Goldenacre_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goldenacre.Core.Goldenacre.Resources", typeof(Goldenacre_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be null..
        /// </summary>
        internal static string ArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an enumeration..
        /// </summary>
        internal static string ArgumentIsNotAnEnum {
            get {
                return ResourceManager.GetString("ArgumentIsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        internal static string ArgumentIsNotValid {
            get {
                return ResourceManager.GetString("ArgumentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not within the allowed range..
        /// </summary>
        internal static string ArgumentIsNotWithinTheAllowedRange {
            get {
                return ResourceManager.GetString("ArgumentIsNotWithinTheAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeKind.Unspecified is not supported..
        /// </summary>
        internal static string DateTimeKindUnspecifiedIsNotSupported {
            get {
                return ResourceManager.GetString("DateTimeKindUnspecifiedIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The from date must not be before the to date..
        /// </summary>
        internal static string FromDateMustNotBeBeforeToDate {
            get {
                return ResourceManager.GetString("FromDateMustNotBeBeforeToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument must not be null..
        /// </summary>
        internal static string SpecifiedArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("SpecifiedArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is not an enumeration..
        /// </summary>
        internal static string SpecifiedArgumentIsNotAnEnum {
            get {
                return ResourceManager.GetString("SpecifiedArgumentIsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is not valid..
        /// </summary>
        internal static string SpecifiedArgumentIsNotValid {
            get {
                return ResourceManager.GetString("SpecifiedArgumentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is not within the allowed range..
        /// </summary>
        internal static string SpecifiedArgumentIsNotWithinTheAllowedRange {
            get {
                return ResourceManager.GetString("SpecifiedArgumentIsNotWithinTheAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified resource was not found..
        /// </summary>
        internal static string SpecifiedResourceNotFound {
            get {
                return ResourceManager.GetString("SpecifiedResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string argument must not be null or empty..
        /// </summary>
        internal static string SpecifiedStringArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SpecifiedStringArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be null or empty..
        /// </summary>
        internal static string StringArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true,1,y,yes,ok,+.
        /// </summary>
        internal static string TruthyStrings {
            get {
                return ResourceManager.GetString("TruthyStrings", resourceCulture);
            }
        }
    }
}
